config/routes.rb
Rails.application.routes.draw do

  resources :characters
    post 'characters/roll-abilities' => 'character#roll_abilities', as: :character_roll_abilities
  resources :ability_scores

end

app/models/ability.rb
class Ability < ActiveRecord::Base
  has_many :characters, through: :ability_scores #works
  has_many :ability_scores #works
end

app/models/ability_score.rb
class AbilityScore < ActiveRecord::Base
  belongs_to :character #works
  belongs_to :ability #works
end

app/models/character.rb
class Character < ActiveRecord::Base
  has_many :ability_scores #works
  has_many :abilities, through: :ability_scores #works
  has_one :character_race_association #works
  has_one :race, through: :character_race_association #works
  has_one :character_class_association #probably works
  has_one :chracter_class, through: :character_class_association #probably works

  accepts_nested_attributes_for :character_race_association
  accepts_nested_attributes_for :ability_scores
end

app/models/character_class.rb
class CharacterClass < ActiveRecord::Base
  has_many :character_class_associations
  has_many :characters, through: :character_class_associations
end

app/models/character_class_association.rb
class CharacterClassAssociation < ActiveRecord::Base
  belongs_to :character
  belongs_to :character_class
end

app/models/character_race_association.rb
class CharacterRaceAssociation < ActiveRecord::Base
  belongs_to :character
  belongs_to :race
end

app/models/race.rb
class Race < ActiveRecord::Base
  has_many :character_race_associations #works
  has_many :characters, through: :character_race_associations #works
end

app/controllers/ability_scores_controller.rb
class AbilityScoresController < ApplicationController
  def new
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def new
    @character = Character.new
    @character.character_race_association = CharacterRaceAssociation.new 
    Ability.all.each do |ability|
      @character.ability_scores << AbilityScore.new(ability_id: ability.id)
    end 
  end

  def create
    @character = Character.new character_params

    if @character.save!
      redirect_to character_path(@character)
    else
      render :new
    end
  end

  def show
    @character = Character.find params[:id]
  end

  def edit
     @character = Character.find params[:id]
  end

  private

  def character_params
    params[:character].permit(
      :name,
      character_race_association_attributes: [
        :id,
        :race_id
      ],
      ability_scores_attributes: [
        :id,
        :ability_id,
        :level_score,
        :experience_score
      ]
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/_form.html.erb
<%= form_for @character do |character_builder| %>
  
  <%= character_builder.text_field :name %> <br />

  <%= character_builder.fields_for :character_race_association do |race_assoc_builder| %>

    <%= race_assoc_builder.select(:race_id, Race.all.map {|race| [race.name, race.id]} ) %>

  <% end%> <br />

 <%= character_builder.fields_for :ability_scores do |ability_score_builder| %>
 <br />
    <%= ability_score_builder.hidden_field(:ability_id, value: ability_score_builder.object.ability.id) %>
    <%= ability_score_builder.number_field(:level_score, min: 0, max: 999) %> /
    <%= ability_score_builder.number_field(:experience_score, min: 0, max: 999) %>

    <%= ability_score_builder.label(:level_score, "#{ability_score_builder.object.ability.name}") %>
  <% end%>

<br />
  <%= character_builder.submit "Create Character" %>

<% end %>

<%= button_to "Roll", character_roll_abilities_path, class: "dice-btn" %>

app/views/characters/edit.html.erb
<h2>Build Your Character</h2>

<%= render 'form' %>

app/views/characters/new.html.erb
<h2>Build Your Character</h2>

<%= render 'form' %>

app/views/characters/show.html.erb
<h2>Name: <%= @character.name %></h2>

<h4>Race: <%= @character.race.name %></h4>
<p><%= @character.race.description %></p>

<%@character.ability_scores.each do |ability_score|%>
  <p><%= ability_score.ability.name %></p>
  <p><%= ability_score.level_score %>/ <%= ability_score.experience_score %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackmaster Character Generator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>